apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: git-repo-secret
  namespace: argocd
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.argocd__>>
  data:
  - key: my-cluster/argocd/https_username
    name: HTTPS_USERNAME
  - key: my-cluster/argocd/https_password
    name: HTTPS_PASSWORD
