apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-rds-secret
  namespace: kubeflow
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.kubeflow__>>
  data:
  - key: my-cluster/kubeflow/rds_username
    name: RDS_USERNAME
  - key: my-cluster/kubeflow/rds_password
    name: RDS_PASSWORD
