apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.auth__>>
  data:
  - key: my-cluster/auth/client_id
    name: client-id
  - key: my-cluster/auth/client_secret
    name: client-secret
  - key: my-cluster/auth/cookie_secret
    name: cookie-secret
