apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: <<__external_secrets.backend_type__>>
  template:
    type: kubernetes.io/tls
  roleArn: <<__role_arn.external_secrets.istio_system__>>
  data:
  - key: my-cluster/istio-system/auth_ca_cert
    name: ca.crt
  - key: my-cluster/istio-system/auth_cert
    name: tls.crt
  - key: my-cluster/istio-system/auth_cert_pk
    name: tls.key
