apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: monitoring-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  dnsNames:
  - grafana.eu-west-1.eksctl.io
  - kiali.eu-west-1.eksctl.io
  - kubecost.eu-west-1.eksctl.io
