kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: my-cluster-instance.xzyabc123456.eu-central-1.rds.amazonaws.com
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: 890123456789-my-cluster-mlflow
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
