kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCgLviIXQULpMnRDjwrYr6cQy1ErLcMla4rETLhLLqZ0HBrfjKojH5c4MFsDWj/NyXImPgox724rualZ9263gpx5+0vUg9mB6BEHbsRrVRf22kpSL7IWh0H3cU5gbIspHNTcsFBOJB57Weakw1AUA6+8pNow/GXGa792hRDRLGcL/2vWJiHE1ATLuL0jj4Yk3jVevkzNHlUqryWbK9Iu9gsN8/Msk0dK1t0cps/Tc9j4jEN8Ldp5wj+dXT4LYBkZihz3P59spwiWVzNeqw9ZxSFRbI+xDBbNUrwuk1zz7Yd3zzvS0G04HMNqBthawa3xWeTFPG6UyeIy8mFt+iOmpvjRy3ZKH4zUwWprtRYODsEa5F9iAF3V2mFTGZeK1J8qHZ+caWoK/fvDza+/cRGb4BfOPYT2O7H7HuebdEO5NtKNS0NkN76ldzzJD+a8N0Fm70gcZrQKo5meLspYF2aup3ISAPxC5iWXtDkjwGQU64G72F5NG74C0Hc1VWwP8VgmMuh0Ea6DNmCHx173rBReg4nGrlJTUt0PZgytu5buktzrsnCFG+IqHPOFoF3EKFaKEweLBv3JVa9BR8PaU4J9AY4uFl4r3xcl3FVd+0SfaaHgG9fe0T/vBc4nmF0rIgFH4GZkaifDbUA6aX8yhYL3e4RuSmSqVNp8/TOutH7WLklxQBMCkMTvyJeUQpx0gM97+ZVnXsB0YgO3D5FSQ==
    admin-user: AgCVReP4/CO7/b4mIuwYsHF+xG7yqQmQik5OEQqs4SOHHxrZ6/TVjKG7Y0qyd6rtM4TuzmQatZuAvz5AdD9sjRGTPX3yEu8/P6TZTG3Ih4EUekG0cppHhRncaEDhCR2TGnXgSSulO1Bv1mvSZCZFxsXddwl84jzF32jDBEqZ+ZPFjN6P/vUduMbtFDO1qiqxHKgh5KLnbMhjeTf34RBOLADh6NsM9GTl3q6wrDNrtCcn/pcxzQDnF+JyJ1PT0TzWyFsYfKQuum2Wb57YqbaOmBmoNQ+5Q3GnkCPh+DmDx0sfozYCS1gc7pe25vQ5Cdiv8DCIig1myzEbcC+DJyft8o7Eg6fu/V9nfAElRK0ALUCOR0bs50eUlC2V1SRAq/RRh2+9Ev+BiG1I3xLKIt4/APcVY6q9Hb/u4ETE/uMtn6eFKZZaJI09+RheqddhJZ5Yzt5VOFrTU7cmdEiHKIYUpnPOhqRCpL/7UZl2lxUfd4f4KWDBXOJp2xLZg3mer7/vV/fpYNyTxYoA7AdHEO40c/MozoAwtUVBM46SaLjY++WkWma1IYvqVUgjM7paEv+iOmT1LiW0kIFL8B+qQWOv2hv+s9NRYRaRcaTX0TrNab/lFLP+Rjz+G1OMXkBZD4+mVMj6lTma8i1YH1G/BPybH0s1XyzpCOPOiWOYHH5ai3b7ZdJkhlz51sw3VAcwabgLyoeac7oj6g==
